package com.intel.thinkscala.turk

object SpeechTopics {
 
  val topics = List(
	"Cheaters never prosper",
	"Cheating at universities is a under-acknowledged problem",
	"The ability for professors to speech freely is paramount to their ability to do valid research",
	"Academic freedom should be constrained by national security",
	"Acid rain is becoming more common and widespread",
	"Acid rain is predominately driven by industrialization",
	"Addiction is an just an excuse used by criminals",
	"Affirmative Action has weakend the US's ability to compete in the global market",
	"Affirmative Action is an effective method for reducing historical ethnic and racial inequalities",
	"Development aid efforts throughout Africa have largely failed",
	"Development aid in Africa is a tool used by western countries to extract natural resources at below market prices",
	"Universal health care always results in age discrimination",
	"Genetically modified foods are dangerous",
	"Genetically modified foods is the best method for reducing starvation related deaths",
	"HIV testing should be mandatory for all public school students",
	"Air pollution is not as important as water pollution",
	"Penalties for DUIs should be increased",
	"Anti-Semitism gets more attention than it deserves",
	"Fully automatic weapons should be sold legally",
	"Artificial Intelligence will never reach human level intelligence",
	"Bigamy should be legal for consenting adults",
	"Bilingual education increases intelligence",
	"Biodiversity is not significantly affected by human actions",
	"Biological and chemical weapons should be used to end conflicts as quickly as possible",
	"Birth control is a universal human right",
	"Breast feeding in public should be banned",
	"Cameras in courtrooms sway court rulings",
	"Campaign financing leads to political corruption",
	"Censorship is necessary to maintain social order",
	"Chat rooms are dangerous for youth",
	"Child abuse is the cause of many future crimes",
	"Child labor should be allowed provided minimal working conditions are met",
	"Consumer protection should be a primary function of the national government",
	"Creationism is false",
	"Diabetes is the result of drinking too much milk",
	"Dieting is not effective",
	"Disabilities should not garner special access",
	"Domestic violence is often drug related",
	"Drug trafficking is our primary national security concern",
	"Steroids should be allowed in professional sports",
	"Drunk driving should result in a life-time driving ban",
	"Endangered species should not be protected",
	"Alternative energy will never be cost effective",
	"Epidemics or exaggerated by the media",
	"Euthanasia should be legalized",
	"Famine relief efforts are not effective",
	"Unhealthy foods should be taxed at a higher rate",
	"Divorces should be taxed by the government",
	"The federal deficit is a national security problem",
	"Feminism hurts women's status",
	"Food borne illnesses are exaggerated by the media",
	"Food safety should be guaranteed by the federal government",
	"Foreign oil dependence is not a national security issue",
	"Foreign policy should focus primarily on economic issues",
	"Fraud should be prosecuted more severely",
	"Gangs are the greatest danger for urban youth",
	"Garbage and waste should be provided by the government",
	"Gay marriages should be legalized",
	"Genetic engineering is the next great technology horizon",
	"Global resources are not constrained",
	"Global warming is a hoax",
	"Globalisation is a net benefit for the world's population",
	"Government deregulation would lead to an increased incidence of fraud",
	"Gun control is a restriction of constitutional rights",
	"Hate crimes should receive the strictest possible penalties",
	"A single payer health care system would improve health care",
	"Home schooling decreases a child's future career success",
	"Homeland security saves American lives",
	"Homeless people are dangerous",
	"Human cloning is inevitable",
	"There are no universal human rights",
	"Illegal immigration takes jobs away from Americans",
	"Inner-city poverty is enabled by government housing",
	"Intellectual property is America's primary asset",
	"Islamic fundamentalism should not be tolerated",
	"Learning disabilities can be effectively treated with psycho-somatic drugs",
	"Legalization of drugs would reduce crime rates",
	"Mass-media should be fined for factual incorrect or misleading reporting",
	"The Middle East peace process is doomed to fail",
	"North Korea is not a real threat to the US",
	"Organ donation should be opt-out",
	"Organized crime weakens the US economy",
	"Overpopulation is not a proven problem",
	"Patriotism leads to descrimination",
	"Peer pressure should be better regulated by teachers and parents",
	"Pesticides cause chronic human health problems",
	"Polygamy is fun",
	"Pornography should be considered art",
	"Poverty should be defined by access to resources",
	"Prison reform is not worth the cost",
	"Privacy should not be a concern with respect to national security",
	"Property rights are the cornerstone of any modern economy",
	"Racism is decreasing",
	"Recycling does not significantly improve the environment",
	"Religions should be eradicated",
	"Reproductive technologies are unsafe",
	"Right to strike should be revoked",
	"School violence is more often psychological than physical",
	"Sex education should be taught public schools",
	"Smoking should be banned in every public space",
	"Space exploration is a waste of resources",
	"Spying/intelligence efforts save American lives",
	"Supremist groups should not be granted free speech",
	"Surrogate motherhood is unnatural",
	"Terrorists acts should be punishable by death",
	"Public transportation should be required",
	"Video games increase cognitive abilities",
	"Voting rights should be limited to people paying taxes",
	"The war on drugs is being lost",
	"Water resources will become our primary environmental issue within the next 50 years",
	"Welfare makes people lazy",
	"Women cause more driving accidents than men")

  val requests = topics map (x => new TurkRequest(x))
  

  
}
